{{- if and .Values.storage.enabled (not .Values.storage.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-tenants
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes: [ReadWriteOnce]
  {{- if .Values.storage.persistence.storageClass }}
  storageClassName: {{ .Values.storage.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.persistence.size }}
{{- end }}
