use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
use utoipa::{Modify, OpenApi};

use crate::dto::auth_dto::{AuthResponseDto, AuthUserDto, LoginDto, RegisterDto, RegisterResponseDto, VerifyOtpDto};
use crate::handlers;
use crate::models::{
    AssignPlanDto, CreateDeviceDto, CreateDeviceGameDto, CreateFileDto, CreateGameDto, CreatePlanDto,
    CreateProductDto, CreateSessionDto, CreateTransactionDto, CreateUnitDto, Device, DeviceFilterDto, FileFilterDto,
    DeviceGameFilterDto, DeviceGameResponse, EndSessionDto, FileRecord, FileWithDownloadUrlDto, Game,
    GameFilterDto, GenerateDownloadUrlDto, GenerateUploadUrlDto, Plan, PlanFilterDto, PlayerPlan,
    PlayerPlanFilterDto, Product, ProductFilterDto, SessionFilterDto, StorageStatsDto, Transaction,
    TransactionFilterDto, Unit, UnitFilterDto, UpdateDeviceDto, UpdateDeviceStatusDto, UpdateFileDto,
    UpdateGameDto, UpdatePlanDto, UpdateProductDto, UpdateUnitDto, UpdateUserDto, UsageSession, User,
    UserFilterDto, ValidationResult,
};
use crate::openapi::responses::*;
use crate::services::stats_service::{
    DashboardStatsDto, DeviceStatsDto, PeriodDto, PeriodPairRevenueByPaymentMethod,
    PeriodPairUsageStats, PlanStatsDto, PlanTypeStat, RevenueByPaymentMethodDto, RevenueTrendDto,
    TopPerformersDto, TransactionStatsDto, UsageStatsDto, UserStatsDto,
};
use crate::services::storage_service::{
    ListObjectsResponse, PresignedDownloadUrlResponse, PresignedUploadUrlResponse, StorageObjectInfo,
};

pub mod responses;

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi.components.get_or_insert_with(Default::default);
        components.add_security_scheme(
            "bearer_auth",
            SecurityScheme::Http(
                HttpBuilder::new()
                    .scheme(HttpAuthScheme::Bearer)
                    .bearer_format("JWT")
                    .description(Some("JWT obtained from POST /auth/verify-otp".to_string()))
                    .build(),
            ),
        );
    }
}

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Game Zone Management System API",
        version = "1.0.0",
        description = "REST API for managing a gaming cafe: users, devices, plans, sessions, transactions, and inventory."
    ),
    servers(
        (url = "http://localhost:3000", description = "Local development server"),
    ),
    paths(
        handlers::health::live_check,
        handlers::health::ready_check,
        handlers::health::health_check_legacy,
        handlers::auth::login_admin,
        handlers::auth::verify_otp,
        handlers::auth::register,
        handlers::stats::dashboard_stats,
        handlers::stats::revenue_by_payment_method,
        handlers::stats::usage_stats,
        handlers::users::list_users,
        handlers::users::get_user,
        handlers::users::update_user,
        handlers::devices::list_devices,
        handlers::devices::get_device,
        handlers::devices::create_device,
        handlers::devices::update_device,
        handlers::devices::update_device_status,
        handlers::devices::delete_device,
        handlers::games::list_games,
        handlers::games::get_game,
        handlers::games::create_game,
        handlers::games::update_game,
        handlers::games::delete_game,
        handlers::plans::list_plans,
        handlers::plans::get_active_plans,
        handlers::plans::get_plan,
        handlers::plans::create_plan,
        handlers::plans::update_plan,
        handlers::plans::delete_plan,
        handlers::player_plans::list_player_plans,
        handlers::player_plans::list_my_active_plans,
        handlers::player_plans::get_best_plan,
        handlers::player_plans::assign_plan,
        handlers::player_plans::get_player_plan,
        handlers::player_plans::validate_access,
        handlers::units::list_units,
        handlers::units::get_unit,
        handlers::units::create_unit,
        handlers::units::update_unit,
        handlers::units::delete_unit,
        handlers::device_games::list_device_games,
        handlers::device_games::list_device_games_by_device,
        handlers::device_games::list_device_games_by_game,
        handlers::device_games::create_device_game,
        handlers::device_games::delete_device_game,
        handlers::sessions::list_sessions,
        handlers::sessions::list_active_sessions,
        handlers::sessions::get_session,
        handlers::sessions::create_session,
        handlers::sessions::end_session,
        handlers::transactions::list_transactions,
        handlers::transactions::get_transaction,
        handlers::transactions::create_transaction,
        handlers::products::list_products,
        handlers::products::get_product,
        handlers::products::create_product,
        handlers::products::update_product,
        handlers::products::delete_product,
        handlers::storage::generate_upload_url,
        handlers::storage::generate_download_url,
        handlers::storage::list_objects,
        handlers::files::list_files,
        handlers::files::get_storage_stats,
        handlers::files::get_file,
        handlers::files::create_file,
        handlers::files::update_file,
        handlers::files::delete_file,
        handlers::files::get_file_download_url,
        handlers::files::archive_file,
        handlers::files::activate_file,
        handlers::sse::sse_handler,
    ),
    components(
        schemas(
            handlers::health::HealthData,
            handlers::health::LiveHealthData,
            handlers::stats::StatsQuery,
            ErrorEnvelope,
            LegacyHealthResponse,
            HealthEnvelope,
            LiveHealthEnvelope,
            LoginDto,
            VerifyOtpDto,
            RegisterDto,
            OtpPendingEnvelope,
            AuthResponseDto,
            AuthUserDto,
            AuthResponseEnvelope,
            RegisterResponseDto,
            RegisterResponseEnvelope,
            DashboardStatsDto,
            DashboardStatsEnvelope,
            PeriodDto,
            PeriodPairRevenueByPaymentMethod,
            RevenueByPaymentMethodEnvelope,
            PeriodPairUsageStats,
            UsageStatsEnvelope,
            RevenueByPaymentMethodDto,
            TransactionStatsDto,
            UsageStatsDto,
            UserStatsDto,
            PlanStatsDto,
            PlanTypeStat,
            DeviceStatsDto,
            TopPerformersDto,
            RevenueTrendDto,
            Device,
            DeviceFilterDto,
            CreateDeviceDto,
            UpdateDeviceDto,
            UpdateDeviceStatusDto,
            DeviceEnvelope,
            DevicePaginationEnvelope,
            DevicePaginationPage,
            Game,
            GameFilterDto,
            CreateGameDto,
            UpdateGameDto,
            GameEnvelope,
            GamePaginationEnvelope,
            GamePaginationPage,
            Plan,
            PlanFilterDto,
            CreatePlanDto,
            UpdatePlanDto,
            PlanEnvelope,
            PlanPaginationEnvelope,
            PlanPaginationPage,
            ActivePlansEnvelope,
            PlayerPlan,
            PlayerPlanFilterDto,
            AssignPlanDto,
            ValidationResult,
            PlayerPlanEnvelope,
            PlayerPlanPaginationEnvelope,
            PlayerPlanPaginationPage,
            ValidationResultEnvelope,
            Unit,
            UnitFilterDto,
            CreateUnitDto,
            UpdateUnitDto,
            UnitEnvelope,
            UnitPaginationEnvelope,
            UnitPaginationPage,
            DeviceGameResponse,
            DeviceGameFilterDto,
            CreateDeviceGameDto,
            DeviceGameEnvelope,
            DeviceGamePaginationEnvelope,
            DeviceGamePaginationPage,
            UsageSession,
            SessionFilterDto,
            CreateSessionDto,
            EndSessionDto,
            SessionEnvelope,
            SessionPaginationEnvelope,
            SessionPaginationPage,
            Transaction,
            TransactionFilterDto,
            CreateTransactionDto,
            TransactionEnvelope,
            TransactionPaginationEnvelope,
            TransactionPaginationPage,
            Product,
            ProductFilterDto,
            CreateProductDto,
            UpdateProductDto,
            ProductEnvelope,
            ProductPaginationEnvelope,
            ProductPaginationPage,
            GenerateUploadUrlDto,
            GenerateDownloadUrlDto,
            PresignedUploadUrlResponse,
            PresignedDownloadUrlResponse,
            PresignedUploadUrlEnvelope,
            PresignedDownloadUrlEnvelope,
            ListObjectsResponse,
            ListObjectsEnvelope,
            StorageObjectInfo,
            FileRecord,
            FileFilterDto,
            CreateFileDto,
            UpdateFileDto,
            FileWithDownloadUrlDto,
            StorageStatsDto,
            FileEnvelope,
            FilePaginationEnvelope,
            FilePaginationPage,
            FileWithDownloadUrlEnvelope,
            StorageStatsEnvelope,
            User,
            UserFilterDto,
            UpdateUserDto,
            UserEnvelope,
            UserPaginationEnvelope,
            UserPaginationPage,
        )
    ),
    modifiers(&SecurityAddon),
    tags(
        (name = "health", description = "Health and readiness probes"),
        (name = "auth", description = "Authentication"),
        (name = "stats", description = "Dashboard statistics"),
        (name = "users", description = "User management"),
        (name = "devices", description = "Device inventory"),
        (name = "games", description = "Game catalog"),
        (name = "plans", description = "Subscription plans"),
        (name = "player-plans", description = "Player plan assignments"),
        (name = "units", description = "Inventory units"),
        (name = "device-games", description = "Device-game assignments"),
        (name = "sessions", description = "Usage sessions"),
        (name = "transactions", description = "Payment transactions"),
        (name = "products", description = "Products"),
        (name = "storage", description = "Object storage presign"),
        (name = "files", description = "File metadata"),
        (name = "sse", description = "Server-sent events"),
    )
)]
pub struct ApiDoc;
