use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
use utoipa::{Modify, OpenApi};

use crate::dto::auth_dto::{
    AuthResponseDto, AuthUserDto, LoginDto, RegisterDto, RegisterResponseDto, VerifyOtpDto,
};
use crate::handlers;
use crate::models::{
    ApproveDepositDto, ApproveExpenseDto, AssignPlanDto, CashDeposit, CashDepositFilterDto,
    CashRegister, CashRegisterEntry, CashRegisterFilterDto, CashRegisterWithEntries, ClockInDto,
    ClockOutDto, CloseCashRegisterDto, ConfigFilterDto, Configuration, CreateCashRegisterEntryDto,
    CreateDeviceDto, CreateDeviceGameDto, CreateExpenseCategoryDto, CreateExpenseDto,
    CreateFileDto, CreateGameDto, CreatePlanDto, CreateProductDto, CreateSessionDto,
    CreateTransactionDto, CreateUnitDto, CreateVendorDto, Device, DeviceFilterDto,
    DeviceGameFilterDto, DeviceGameResponse, EndSessionDto, Expense, ExpenseCategory,
    ExpenseCategoryFilterDto, ExpenseFilterDto, ExpenseSummaryDto, FileFilterDto, FileRecord,
    FileWithDownloadUrlDto, Game, GameFilterDto, GenerateDownloadUrlDto, GenerateUploadUrlDto,
    HandoverDepositDto, InitiateDepositDto, OpenCashRegisterDto, Plan, PlanFilterDto, PlayerPlan,
    PlayerPlanFilterDto, Product, ProductFilterDto, RejectDepositDto, RejectExpenseDto,
    SessionFilterDto, Shift, ShiftFilterDto, ShiftHandoverDto, ShiftHandoverResponseDto,
    StorageStatsDto, Transaction, TransactionFilterDto, TotpSetupResponseDto, Unit, UnitFilterDto,
    UpdateDeviceDto, UpdateDeviceGameDto, UpdateDeviceStatusDto, UpdateExpenseCategoryDto,
    UpdateExpenseDto, UpdateFileDto, UpdateGameDto, UpdatePlanDto, UpdateProductDto,
    UpdateTransactionDto, UpdateUnitDto, UpdateUserDto, UpdateVendorDto, UpsertConfigDto,
    UsageSession, UsageSessionResponse, User, UserFilterDto, ValidationResult, Vendor,
    VendorFilterDto, VerifyTotpSetupDto,
};
use crate::openapi::responses::*;
use crate::services::stats_service::{
    DashboardStatsDto, DeviceStatsDto, PeriodDto, PeriodPairRevenueByPaymentMethod,
    PeriodPairUsageStats, PlanStatsDto, PlanTypeStat, RevenueByPaymentMethodDto, RevenueTrendDto,
    StaffDashboardStatsDto, StaffDeviceStatsDto, StaffPlayerStatsDto, TopPerformersDto,
    TransactionStatsDto, UsageStatsDto, UserStatsDto,
};
use crate::services::storage_service::{
    ListObjectsResponse, PresignedDownloadUrlResponse, PresignedUploadUrlResponse,
    StorageObjectInfo,
};

pub mod responses;

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi.components.get_or_insert_with(Default::default);
        components.add_security_scheme(
            "bearer_auth",
            SecurityScheme::Http(
                HttpBuilder::new()
                    .scheme(HttpAuthScheme::Bearer)
                    .bearer_format("JWT")
                    .description(Some("JWT obtained from POST /auth/verify-otp".to_string()))
                    .build(),
            ),
        );
    }
}

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Game Zone Management System API",
        version = "1.0.0",
        description = "REST API for managing a gaming cafe: users, devices, plans, sessions, transactions, and inventory."
    ),
    servers(
        (url = "http://localhost:3000", description = "Local development server"),
    ),
    paths(
        handlers::health::live_check,
        handlers::health::ready_check,
        handlers::health::health_check_legacy,
        handlers::auth::login_admin,
        handlers::auth::login_staff,
        handlers::auth::verify_otp,
        handlers::auth::register,
        handlers::stats::dashboard_stats,
        handlers::stats::staff_dashboard_stats,
        handlers::stats::revenue_by_payment_method,
        handlers::stats::usage_stats,
        handlers::users::list_users,
        handlers::users::get_user,
        handlers::users::update_user,
        handlers::users::setup_totp,
        handlers::users::verify_totp_setup,
        handlers::users::disable_totp,
        handlers::devices::list_devices,
        handlers::devices::get_device,
        handlers::devices::create_device,
        handlers::devices::update_device,
        handlers::devices::update_device_status,
        handlers::devices::delete_device,
        handlers::games::list_games,
        handlers::games::get_game,
        handlers::games::create_game,
        handlers::games::update_game,
        handlers::games::delete_game,
        handlers::plans::list_plans,
        handlers::plans::get_active_plans,
        handlers::plans::get_plan,
        handlers::plans::create_plan,
        handlers::plans::update_plan,
        handlers::plans::delete_plan,
        handlers::player_plans::list_player_plans,
        handlers::player_plans::list_my_active_plans,
        handlers::player_plans::get_best_plan,
        handlers::player_plans::assign_plan,
        handlers::player_plans::get_player_plan,
        handlers::player_plans::validate_access,
        handlers::units::list_units,
        handlers::units::get_unit,
        handlers::units::create_unit,
        handlers::units::update_unit,
        handlers::units::delete_unit,
        handlers::device_games::list_device_games,
        handlers::device_games::list_device_games_by_device,
        handlers::device_games::list_device_games_by_game,
        handlers::device_games::create_device_game,
        handlers::device_games::get_device_game,
        handlers::device_games::update_device_game,
        handlers::device_games::delete_device_game,
        handlers::sessions::list_sessions,
        handlers::sessions::list_active_sessions,
        handlers::sessions::get_session,
        handlers::sessions::create_session,
        handlers::sessions::end_session,
        handlers::transactions::list_transactions,
        handlers::transactions::get_transaction,
        handlers::transactions::create_transaction,
        handlers::transactions::update_transaction,
        handlers::products::list_products,
        handlers::products::get_product,
        handlers::products::create_product,
        handlers::products::update_product,
        handlers::products::delete_product,
        handlers::storage::generate_upload_url,
        handlers::storage::generate_download_url,
        handlers::storage::list_objects,
        handlers::files::list_files,
        handlers::files::get_storage_stats,
        handlers::files::get_file,
        handlers::files::create_file,
        handlers::files::update_file,
        handlers::files::delete_file,
        handlers::files::get_file_download_url,
        handlers::files::archive_file,
        handlers::files::activate_file,
        handlers::sse::sse_handler,
        handlers::config::list_config,
        handlers::config::get_config,
        handlers::config::upsert_config,
        handlers::shifts::clock_in,
        handlers::shifts::clock_out,
        handlers::shifts::handover_shift,
        handlers::shifts::get_active_shift,
        handlers::shifts::list_shifts,
        handlers::shifts::get_shift,
        handlers::shifts::force_close_shift,
        handlers::cash_registers::open_cash_register,
        handlers::cash_registers::close_cash_register,
        handlers::cash_registers::add_entry,
        handlers::cash_registers::get_cash_register,
        handlers::cash_registers::list_cash_registers,
        handlers::cash_registers::get_active_expected_closing,
        handlers::cash_deposits::initiate_deposit,
        handlers::cash_deposits::list_deposits,
        handlers::cash_deposits::get_deposit,
        handlers::cash_deposits::approve_deposit,
        handlers::cash_deposits::reject_deposit,
        handlers::expense_categories::list_expense_categories,
        handlers::expense_categories::get_expense_category,
        handlers::expense_categories::create_expense_category,
        handlers::expense_categories::update_expense_category,
        handlers::expense_categories::delete_expense_category,
        handlers::vendors::list_vendors,
        handlers::vendors::get_vendor,
        handlers::vendors::create_vendor,
        handlers::vendors::update_vendor,
        handlers::vendors::delete_vendor,
        handlers::expenses::list_expenses,
        handlers::expenses::get_expense,
        handlers::expenses::create_expense,
        handlers::expenses::update_expense,
        handlers::expenses::approve_expense,
        handlers::expenses::reject_expense,
        handlers::expenses::expense_summary,
    ),
    components(
        schemas(
            handlers::health::HealthData,
            handlers::health::LiveHealthData,
            handlers::stats::StatsQuery,
            handlers::stats::StaffStatsQuery,
            ErrorEnvelope,
            LegacyHealthResponse,
            HealthEnvelope,
            LiveHealthEnvelope,
            LoginDto,
            VerifyOtpDto,
            RegisterDto,
            OtpPendingEnvelope,
            AuthResponseDto,
            AuthUserDto,
            AuthResponseEnvelope,
            RegisterResponseDto,
            RegisterResponseEnvelope,
            DashboardStatsDto,
            DashboardStatsEnvelope,
            StaffDashboardStatsDto,
            StaffDashboardStatsEnvelope,
            StaffPlayerStatsDto,
            StaffDeviceStatsDto,
            PeriodDto,
            PeriodPairRevenueByPaymentMethod,
            RevenueByPaymentMethodEnvelope,
            PeriodPairUsageStats,
            UsageStatsEnvelope,
            RevenueByPaymentMethodDto,
            TransactionStatsDto,
            UsageStatsDto,
            UserStatsDto,
            PlanStatsDto,
            PlanTypeStat,
            DeviceStatsDto,
            TopPerformersDto,
            RevenueTrendDto,
            Device,
            DeviceFilterDto,
            CreateDeviceDto,
            UpdateDeviceDto,
            UpdateDeviceStatusDto,
            DeviceEnvelope,
            DevicePaginationEnvelope,
            DevicePaginationPage,
            Game,
            GameFilterDto,
            CreateGameDto,
            UpdateGameDto,
            GameEnvelope,
            GamePaginationEnvelope,
            GamePaginationPage,
            Plan,
            PlanFilterDto,
            CreatePlanDto,
            UpdatePlanDto,
            PlanEnvelope,
            PlanPaginationEnvelope,
            PlanPaginationPage,
            ActivePlansEnvelope,
            PlayerPlan,
            PlayerPlanResponse,
            PlayerPlanFilterDto,
            AssignPlanDto,
            ValidationResult,
            PlayerPlanEnvelope,
            PlayerPlanFlatEnvelope,
            PlayerPlanPaginationEnvelope,
            PlayerPlanPaginationPage,
            ValidationResultEnvelope,
            Unit,
            UnitFilterDto,
            CreateUnitDto,
            UpdateUnitDto,
            UnitEnvelope,
            UnitPaginationEnvelope,
            UnitPaginationPage,
            DeviceGameResponse,
            DeviceGameFilterDto,
            CreateDeviceGameDto,
            UpdateDeviceGameDto,
            DeviceGameEnvelope,
            DeviceGamePaginationEnvelope,
            DeviceGamePaginationPage,
            UsageSession,
            UsageSessionResponse,
            SessionFilterDto,
            CreateSessionDto,
            EndSessionDto,
            SessionEnvelope,
            SessionFlatEnvelope,
            SessionPaginationEnvelope,
            SessionPaginationPage,
            Transaction,
            TransactionFilterDto,
            CreateTransactionDto,
            UpdateTransactionDto,
            TransactionEnvelope,
            TransactionPaginationEnvelope,
            TransactionPaginationPage,
            Product,
            ProductFilterDto,
            CreateProductDto,
            UpdateProductDto,
            ProductEnvelope,
            ProductPaginationEnvelope,
            ProductPaginationPage,
            GenerateUploadUrlDto,
            GenerateDownloadUrlDto,
            PresignedUploadUrlResponse,
            PresignedDownloadUrlResponse,
            PresignedUploadUrlEnvelope,
            PresignedDownloadUrlEnvelope,
            ListObjectsResponse,
            ListObjectsEnvelope,
            StorageObjectInfo,
            FileRecord,
            FileFilterDto,
            CreateFileDto,
            UpdateFileDto,
            FileWithDownloadUrlDto,
            StorageStatsDto,
            FileEnvelope,
            FilePaginationEnvelope,
            FilePaginationPage,
            FileWithDownloadUrlEnvelope,
            StorageStatsEnvelope,
            User,
            UserFilterDto,
            UpdateUserDto,
            UserEnvelope,
            UserPaginationEnvelope,
            UserPaginationPage,
            Shift,
            ShiftFilterDto,
            ClockInDto,
            ClockOutDto,
            ShiftEnvelope,
            ShiftActiveEnvelope,
            ShiftPaginationEnvelope,
            ShiftPaginationPage,
            Configuration,
            ConfigFilterDto,
            UpsertConfigDto,
            ShiftHandoverDto,
            ShiftHandoverResponseDto,
            ShiftHandoverResponseEnvelope,
            TotpSetupResponseDto,
            VerifyTotpSetupDto,
            TotpSetupEnvelope,
            ExpectedClosingEnvelope,
            CashDeposit,
            CashDepositFilterDto,
            InitiateDepositDto,
            ApproveDepositDto,
            RejectDepositDto,
            HandoverDepositDto,
            CashDepositEnvelope,
            CashDepositPaginationEnvelope,
            CashDepositPaginationPage,
            ConfigurationEnvelope,
            ConfigurationListEnvelope,
            CashRegister,
            CashRegisterEntry,
            CashRegisterWithEntries,
            CashRegisterFilterDto,
            OpenCashRegisterDto,
            CloseCashRegisterDto,
            CreateCashRegisterEntryDto,
            CashRegisterEnvelope,
            CashRegisterWithEntriesEnvelope,
            CashRegisterEntryEnvelope,
            CashRegisterEntriesEnvelope,
            CashRegisterPaginationEnvelope,
            CashRegisterPaginationPage,
            ExpenseCategory,
            ExpenseCategoryFilterDto,
            CreateExpenseCategoryDto,
            UpdateExpenseCategoryDto,
            ExpenseCategoryEnvelope,
            ExpenseCategoryPaginationEnvelope,
            ExpenseCategoryPaginationPage,
            Vendor,
            VendorFilterDto,
            CreateVendorDto,
            UpdateVendorDto,
            VendorEnvelope,
            VendorPaginationEnvelope,
            VendorPaginationPage,
            Expense,
            ExpenseFilterDto,
            CreateExpenseDto,
            UpdateExpenseDto,
            ApproveExpenseDto,
            RejectExpenseDto,
            ExpenseSummaryDto,
            ExpenseEnvelope,
            ExpenseSummaryListEnvelope,
            ExpensePaginationEnvelope,
            ExpensePaginationPage,
        )
    ),
    modifiers(&SecurityAddon),
    tags(
        (name = "health", description = "Health and readiness probes"),
        (name = "auth", description = "Authentication"),
        (name = "stats", description = "Dashboard statistics"),
        (name = "users", description = "User management"),
        (name = "devices", description = "Device inventory"),
        (name = "games", description = "Game catalog"),
        (name = "plans", description = "Subscription plans"),
        (name = "player-plans", description = "Player plan assignments"),
        (name = "units", description = "Inventory units"),
        (name = "device-games", description = "Device-game assignments"),
        (name = "sessions", description = "Usage sessions"),
        (name = "transactions", description = "Payment transactions"),
        (name = "products", description = "Products"),
        (name = "storage", description = "Object storage presign"),
        (name = "files", description = "File metadata"),
        (name = "shifts", description = "Staff shift management"),
        (name = "cash-registers", description = "Cash register management"),
        (name = "config", description = "Business configuration"),
        (name = "expense-categories", description = "Expense category management"),
        (name = "vendors", description = "Vendor management"),
        (name = "expenses", description = "Expense tracking and approval"),
        (name = "sse", description = "Server-sent events"),
    )
)]
pub struct ApiDoc;
