image:
  repository: harishmahamure/arena360
  tag: frontend-prod-latest
  pullPolicy: Always

imagePullSecrets:
  - name: dockerhub-secret

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: staff.arena360.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: arena360-frontend-new-prod-tls
      hosts:
        - staff.arena360.cloud

env:
  VITE_API_URL: https://api.arena360.cloud
  VITE_GATEWAY_URL: wss://api.arena360.cloud/realtime
