postgresql:
  auth:
    username: arena360
    database: arena360
    existingSecret: arena360-postgresql-secrets
  persistence:
    enabled: true
    storageClassName: ""
    size: 50Gi

pgbouncer:
  replicaCount: 2
  externalService:
    enabled: true
    type: NodePort
    port: 5433
    nodePort: 30433
    annotations: {}
    loadBalancerIP: ""
  config:
    poolMode: transaction
    maxClientConn: 300
    defaultPoolSize: 30
    reservePoolSize: 10

secret:
  create: false
  name: arena360-postgresql-secrets
