apiVersion: v1
kind: Service
metadata:
  name: {{ include "arena360-postgresql.postgresServiceName" . }}
  labels:
    {{- include "arena360-postgresql.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "arena360-postgresql.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
