{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arena360-postgresql.secretName" . }}
  labels:
    {{- include "arena360-postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.secret.password | quote }}
  postgres-password: {{ .Values.secret.postgresPassword | quote }}
  pgbouncer-users.txt: {{ .Values.secret.pgbouncerUsers | quote }}
{{- end }}
