import { Permission } from '@gaming-cafe/contracts';
import {
  AccountBalanceWallet,
  Assessment,
  Balance,
  CardMembership,
  CreditCard,
  Dashboard,
  Devices,
  GridView,
  History,
  Inventory,
  Inventory2,
  MoneyOff,
  People,
  PlayCircle,
  PointOfSale,
  Receipt,
  Restaurant,
  Sell,
  Settings,
  SportsEsports,
  Store,
  WorkHistory,
} from '@mui/icons-material';
import type { AdminNavItem } from '../utils/filterNavItems';
import { analyticsDashboards } from './analyticsDashboards';

/**
 * Canonical panel module registry. Navigation, permission filtering, route titles,
 * breadcrumbs, and command-search metadata are all derived from this structure.
 */
export const moduleRegistry: AdminNavItem[] = [
  {
    title: 'Access management',
    path: '/access',
    icon: <People />,
    section: 'Administration',
    requiredPermission: Permission.AccessRead,
  },
  {
    title: 'Overview',
    path: '/',
    icon: <Dashboard />,
    section: 'Workspace',
    requiredPermission: Permission.StatsRead,
  },
  {
    title: 'Business dashboard',
    path: '/analytics',
    icon: <Assessment />,
    section: 'Workspace',
    requiredPermission: Permission.FinanceRead,
    searchKeywords: ['reports', 'retention', 'forecast', 'capacity', 'pricing', 'membership'],
    children: analyticsDashboards.map((dashboard) => ({
      title: dashboard.title,
      path: `/analytics/${dashboard.id}`,
    })),
  },
  {
    title: 'Sessions',
    path: '/sessions',
    icon: <PlayCircle />,
    section: 'Floor Operations',
    requiredPermission: Permission.SessionsRead,
    children: [
      { title: 'All Sessions', path: '/sessions' },
      {
        title: 'Start New Session',
        path: '/sessions/new',
        requiredPermission: Permission.SessionsWrite,
      },
      { title: 'Active Sessions', path: '/sessions?active=true' },
      { title: 'Completed Sessions', path: '/sessions?active=false' },
    ],
  },
  {
    title: 'Stations',
    path: '/stations',
    icon: <GridView />,
    section: 'Floor Operations',
    requiredPermission: Permission.DevicesRead,
  },
  {
    title: 'Kitchen',
    path: '/kitchen',
    icon: <Restaurant />,
    section: 'Floor Operations',
    requiredPermission: Permission.KitchenRead,
  },
  {
    title: 'Plan sales',
    path: '/plan-transactions',
    icon: <Receipt />,
    section: 'Sales',
    requiredPermission: Permission.PlayerPlansRead,
    children: [
      { title: 'All Transactions', path: '/plan-transactions' },
      {
        title: 'Buy plan',
        path: '/plan-transactions/new',
        requiredPermission: Permission.PlayerPlansWrite,
      },
      { title: 'Pending', path: '/plan-transactions?status=pending' },
      { title: 'Completed', path: '/plan-transactions?status=completed' },
      { title: 'Failed', path: '/plan-transactions?status=failed' },
    ],
  },
  {
    title: 'POS sales',
    path: '/product-transactions',
    icon: <Sell />,
    section: 'Sales',
    requiredPermission: Permission.TransactionsRead,
    children: [
      { title: 'All Sold Items', path: '/product-transactions' },
      {
        title: 'Sell New Items',
        path: '/product-transactions/new',
        requiredPermission: Permission.TransactionsWrite,
      },
      {
        title: 'Pending Transactions',
        path: '/product-transactions?status=pending',
      },
      {
        title: 'Completed Transactions',
        path: '/product-transactions?status=completed',
      },
      {
        title: 'Kiosk orders',
        path: '/kiosk-orders',
        requiredPermission: Permission.TransactionsRead,
      },
    ],
  },
  {
    title: 'Running tab',
    path: '/credit',
    icon: <CreditCard />,
    section: 'Sales',
    requiredPermission: Permission.CreditRead,
    children: [
      { title: 'Outstanding', path: '/credit' },
      { title: 'Settlement history', path: '/credit/settlements' },
    ],
  },
  {
    title: 'Players',
    path: '/players',
    icon: <People />,
    section: 'People & catalog',
    requiredPermission: Permission.PlayersRead,
    children: [
      { title: 'All Players', path: '/players' },
      {
        title: 'Add Player',
        path: '/players/new',
        requiredPermission: Permission.PlayersWrite,
      },
      { title: 'Inactive', path: '/players?active=false' },
    ],
  },
  {
    title: 'Products',
    path: '/products',
    icon: <Inventory />,
    section: 'People & catalog',
    requiredPermission: Permission.ProductsRead,
    children: [
      { title: 'All Products', path: '/products' },
      {
        title: 'Add Product',
        path: '/products/new',
        requiredPermission: Permission.ProductsWrite,
      },
      { title: 'Expiring Soon', path: '/products?stockExpiringSoon=true' },
      { title: 'Inactive Products', path: '/products?deleted=true' },
    ],
  },
  {
    title: 'Inventory',
    path: '/inventory',
    icon: <Inventory2 />,
    section: 'Inventory & supply',
    requiredPermission: Permission.InventoryRead,
    children: [
      { title: 'Control center', path: '/inventory' },
      {
        title: 'Locations',
        path: '/inventory/locations',
        requiredPermission: Permission.InventoryManage,
      },
      { title: 'Stock overview', path: '/inventory/stock' },
      { title: 'Movement ledger', path: '/inventory/movements' },
      {
        title: 'Purchase orders',
        path: '/inventory/purchase-orders',
        requiredPermission: Permission.ProcurementRead,
      },
      {
        title: 'Reorder controls',
        path: '/inventory/reorder',
        requiredPermission: Permission.ProcurementRead,
      },
      {
        title: 'Exceptional intake',
        path: '/inventory/warehouse',
        requiredPermission: Permission.InventoryManage,
      },
      { title: 'Transfer requests', path: '/inventory/transfers' },
      {
        title: 'New transfer request',
        path: '/inventory/transfers/new',
        requiredPermission: Permission.InventoryTransferRequest,
      },
      {
        title: 'Record waste',
        path: '/inventory/waste/new',
        requiredPermission: Permission.InventoryWasteRecord,
      },
      { title: 'Waste approvals', path: '/inventory/waste' },
      { title: 'Waste report', path: '/inventory/waste/report' },
      { title: 'Receipt report', path: '/inventory/receipts/report' },
    ],
  },
  {
    title: 'Games',
    path: '/games',
    icon: <SportsEsports />,
    section: 'People & catalog',
    requiredPermission: Permission.GamesRead,
    children: [
      { title: 'All Games', path: '/games' },
      {
        title: 'Add Game',
        path: '/games/new',
        requiredPermission: Permission.GamesWrite,
      },
    ],
  },
  {
    title: 'Plans',
    path: '/plans',
    icon: <CardMembership />,
    section: 'People & catalog',
    requiredPermission: Permission.PlansRead,
    children: [
      { title: 'All Plans', path: '/plans' },
      {
        title: 'Add Plan',
        path: '/plans/new',
        requiredPermission: Permission.PlansWrite,
      },
      { title: 'Time Based', path: '/plans?planType=time_based' },
      { title: 'Session Based', path: '/plans?planType=session_based' },
      { title: 'Unlimited Daily', path: '/plans?planType=unlimited_daily' },
      {
        title: 'Monthly Subscription',
        path: '/plans?planType=monthly_subscription',
      },
      { title: 'Inactive Plans', path: '/plans?isActive=false' },
    ],
  },
  {
    title: 'Devices',
    path: '/devices',
    icon: <Devices />,
    section: 'People & catalog',
    requiredPermission: Permission.DevicesRead,
    children: [
      { title: 'All Devices', path: '/devices' },
      {
        title: 'Add Device',
        path: '/devices/new',
        requiredPermission: Permission.DevicesWrite,
      },
      { title: 'Operational', path: '/devices?status=operational' },
      { title: 'Maintenance', path: '/devices?status=under_maintenance' },
      { title: 'Out of Order', path: '/devices?status=out_of_service' },
    ],
  },
  {
    title: 'Financial reports',
    path: '/finance/reports',
    icon: <Assessment />,
    section: 'Finance',
    requiredPermission: Permission.FinanceRead,
  },
  {
    title: 'Shifts',
    path: '/shifts',
    icon: <WorkHistory />,
    section: 'Finance',
    requiredPermission: Permission.ShiftsRead,
  },
  {
    title: 'Reconciliation',
    path: '/finance/reconciliation',
    icon: <PointOfSale />,
    section: 'Finance',
    requiredPermission: Permission.FinanceRead,
  },
  {
    title: 'Deposit dashboard',
    path: '/finance/deposits',
    icon: <AccountBalanceWallet />,
    section: 'Finance',
    requiredPermission: Permission.FinanceRead,
  },
  {
    title: 'Variance',
    path: '/finance/variance',
    icon: <Balance />,
    section: 'Finance',
    requiredPermission: Permission.FinanceRead,
  },
  {
    title: 'Cash Registers',
    path: '/cash-registers',
    icon: <PointOfSale />,
    section: 'Finance',
    requiredPermission: Permission.CashRegistersRead,
  },
  {
    title: 'Cash Deposits',
    path: '/cash-deposits',
    icon: <AccountBalanceWallet />,
    section: 'Finance',
    requiredPermission: Permission.CashDepositsRead,
    children: [
      { title: 'All Deposits', path: '/cash-deposits' },
      { title: 'Pending Approval', path: '/cash-deposits?status=pending' },
      { title: 'Approved', path: '/cash-deposits?status=approved' },
    ],
  },
  {
    title: 'Expenses',
    path: '/expenses',
    icon: <MoneyOff />,
    section: 'Finance',
    requiredPermission: Permission.ExpensesRead,
    children: [
      { title: 'All Expenses', path: '/expenses' },
      {
        title: 'Add Expense',
        path: '/expenses/new',
        requiredPermission: Permission.ExpensesWrite,
      },
      { title: 'Pending Approval', path: '/expenses?status=pending' },
      { title: 'Approved', path: '/expenses?status=approved' },
    ],
  },
  {
    title: 'Vendors',
    path: '/vendors',
    icon: <Store />,
    section: 'Inventory & supply',
    requiredPermission: Permission.VendorsRead,
  },
  {
    title: 'Activity log',
    path: '/activity-log',
    icon: <History />,
    section: 'Administration',
    requiredPermission: Permission.ActivityRead,
  },
  {
    title: 'Configuration',
    path: '/settings',
    icon: <Settings />,
    section: 'Administration',
    requiredPermission: Permission.SettingsRead,
  },
];

const WORKSPACE_ORDER = [
  'Workspace',
  'Floor Operations',
  'Sales',
  'People & catalog',
  'Inventory & supply',
  'Finance',
  'Administration',
];

export const adminNavItems = [...moduleRegistry].sort(
  (left, right) =>
    WORKSPACE_ORDER.indexOf(left.section ?? '') - WORKSPACE_ORDER.indexOf(right.section ?? ''),
);
