import { Permission } from '@gaming-cafe/contracts';
import {
  AccountBalanceWallet,
  CardMembership,
  CreditCard,
  Dashboard,
  Devices,
  Inventory,
  Inventory2,
  MoneyOff,
  People,
  PlayCircle,
  PointOfSale,
  Receipt,
  Sell,
  Settings,
  SportsEsports,
  Store,
  WorkHistory,
} from '@mui/icons-material';
import type { AdminNavItem } from '../utils/filterNavItems';

export const adminNavItems: AdminNavItem[] = [
  { title: 'Dashboard', path: '/', icon: <Dashboard />, requiredPermission: Permission.StatsRead },
  {
    title: 'Sessions',
    path: '/sessions',
    icon: <PlayCircle />,
    requiredPermission: Permission.SessionsRead,
    children: [
      { title: 'All Sessions', path: '/sessions' },
      {
        title: 'Start New Session',
        path: '/sessions/new',
        requiredPermission: Permission.SessionsWrite,
      },
      { title: 'Active Sessions', path: '/sessions?active=true' },
      { title: 'Completed Sessions', path: '/sessions?active=false' },
    ],
  },
  {
    title: 'Players',
    path: '/players',
    icon: <People />,
    requiredPermission: Permission.PlayersRead,
    children: [
      { title: 'All Players', path: '/players' },
      {
        title: 'Add Player',
        path: '/players/new',
        requiredPermission: Permission.PlayersWrite,
      },
      { title: 'Staff', path: '/players?role=staff' },
      { title: 'Admins', path: '/players?role=admin' },
      { title: 'Inactive', path: '/players?active=false' },
    ],
  },
  {
    title: 'Plan sales',
    path: '/plan-transactions',
    icon: <Receipt />,
    requiredPermission: Permission.PlayerPlansRead,
    children: [
      { title: 'All Transactions', path: '/plan-transactions' },
      {
        title: 'Buy plan',
        path: '/plan-transactions/new',
        requiredPermission: Permission.PlayerPlansWrite,
      },
      { title: 'Pending', path: '/plan-transactions?status=pending' },
      { title: 'Completed', path: '/plan-transactions?status=completed' },
      { title: 'Failed', path: '/plan-transactions?status=failed' },
    ],
  },
  {
    title: 'Products',
    path: '/products',
    icon: <Inventory />,
    requiredPermission: Permission.ProductsRead,
    children: [
      { title: 'All Products', path: '/products' },
      {
        title: 'Add Product',
        path: '/products/new',
        requiredPermission: Permission.ProductsWrite,
      },
      {
        title: 'Units',
        path: '/units',
        requiredPermission: Permission.UnitsRead,
      },
      { title: 'Expiring Soon', path: '/products?stockExpiringSoon=true' },
      { title: 'Inactive Products', path: '/products?deleted=true' },
    ],
  },
  {
    title: 'Inventory',
    path: '/inventory/locations',
    icon: <Inventory2 />,
    requiredPermission: Permission.InventoryRead,
    children: [
      {
        title: 'Locations',
        path: '/inventory/locations',
        requiredPermission: Permission.InventoryManage,
      },
      { title: 'Warehouse stock', path: '/inventory/warehouse' },
      { title: 'Transfer requests', path: '/inventory/transfers' },
      {
        title: 'New transfer request',
        path: '/inventory/transfers/new',
        requiredPermission: Permission.InventoryTransferRequest,
      },
      {
        title: 'Record waste',
        path: '/inventory/waste/new',
        requiredPermission: Permission.InventoryWasteRecord,
      },
      { title: 'Waste approvals', path: '/inventory/waste' },
      { title: 'Waste report', path: '/inventory/waste/report' },
    ],
  },
  {
    title: 'Games',
    path: '/games',
    icon: <SportsEsports />,
    requiredPermission: Permission.GamesRead,
    children: [
      { title: 'All Games', path: '/games' },
      {
        title: 'Add Game',
        path: '/games/new',
        requiredPermission: Permission.GamesWrite,
      },
    ],
  },
  {
    title: 'POS sales',
    path: '/product-transactions',
    icon: <Sell />,
    requiredPermission: Permission.TransactionsRead,
    children: [
      { title: 'All Sold Items', path: '/product-transactions' },
      {
        title: 'Sell New Items',
        path: '/product-transactions/new',
        requiredPermission: Permission.TransactionsWrite,
      },
      {
        title: 'Pending Transactions',
        path: '/product-transactions?status=pending',
      },
      {
        title: 'Completed Transactions',
        path: '/product-transactions?status=completed',
      },
    ],
  },
  {
    title: 'Devices',
    path: '/devices',
    icon: <Devices />,
    requiredPermission: Permission.DevicesRead,
    children: [
      { title: 'All Devices', path: '/devices' },
      {
        title: 'Add Device',
        path: '/devices/new',
        requiredPermission: Permission.DevicesWrite,
      },
      { title: 'Operational', path: '/devices?status=operational' },
      { title: 'Maintenance', path: '/devices?status=under_maintenance' },
      { title: 'Out of Order', path: '/devices?status=out_of_service' },
    ],
  },
  {
    title: 'Plans',
    path: '/plans',
    icon: <CardMembership />,
    requiredPermission: Permission.PlansRead,
    children: [
      { title: 'All Plans', path: '/plans' },
      {
        title: 'Add Plan',
        path: '/plans/new',
        requiredPermission: Permission.PlansWrite,
      },
      { title: 'Time Based', path: '/plans?planType=time_based' },
      { title: 'Session Based', path: '/plans?planType=session_based' },
      { title: 'Unlimited Daily', path: '/plans?planType=unlimited_daily' },
      {
        title: 'Monthly Subscription',
        path: '/plans?planType=monthly_subscription',
      },
      { title: 'Inactive Plans', path: '/plans?isActive=false' },
    ],
  },
  {
    title: 'Shifts',
    path: '/shifts',
    icon: <WorkHistory />,
    requiredPermission: Permission.ShiftsRead,
  },
  {
    title: 'Cash Registers',
    path: '/cash-registers',
    icon: <PointOfSale />,
    requiredPermission: Permission.CashRegistersRead,
  },
  {
    title: 'Cash Deposits',
    path: '/cash-deposits',
    icon: <AccountBalanceWallet />,
    requiredPermission: Permission.CashDepositsRead,
    children: [
      { title: 'All Deposits', path: '/cash-deposits' },
      { title: 'Pending Approval', path: '/cash-deposits?status=pending' },
      { title: 'Approved', path: '/cash-deposits?status=approved' },
    ],
  },
  {
    title: 'Running tab',
    path: '/credit',
    icon: <CreditCard />,
    requiredPermission: Permission.CreditRead,
  },
  {
    title: 'Expenses',
    path: '/expenses',
    icon: <MoneyOff />,
    requiredPermission: Permission.ExpensesRead,
    children: [
      { title: 'All Expenses', path: '/expenses' },
      {
        title: 'Add Expense',
        path: '/expenses/new',
        requiredPermission: Permission.ExpensesWrite,
      },
      { title: 'Pending Approval', path: '/expenses?status=pending' },
      { title: 'Approved', path: '/expenses?status=approved' },
    ],
  },
  {
    title: 'Vendors',
    path: '/vendors',
    icon: <Store />,
    requiredPermission: Permission.VendorsRead,
  },
  {
    title: 'Settings',
    path: '/settings',
    icon: <Settings />,
    requiredPermission: Permission.ConfigRead,
  },
];
