DROP TRIGGER IF EXISTS analytics_capture ON transactions;
DROP TRIGGER IF EXISTS analytics_capture ON credit_settlements;
DROP TRIGGER IF EXISTS analytics_capture ON credit_settlement_items;
DROP TRIGGER IF EXISTS analytics_capture ON usage_sessions;
DROP TRIGGER IF EXISTS analytics_capture ON users;
DROP TRIGGER IF EXISTS analytics_capture ON plans;
DROP TRIGGER IF EXISTS analytics_capture ON player_plan_balances;
DROP TRIGGER IF EXISTS analytics_capture ON devices;
DROP TRIGGER IF EXISTS analytics_capture ON cash_registers;
DROP TRIGGER IF EXISTS analytics_capture ON cash_deposits;
DROP TRIGGER IF EXISTS analytics_capture ON expenses;
DROP TRIGGER IF EXISTS analytics_capture ON expense_categories;
DROP TRIGGER IF EXISTS analytics_capture ON products;
DROP TRIGGER IF EXISTS analytics_capture ON vendors;
DROP TRIGGER IF EXISTS analytics_capture ON inventory_locations;
DROP TRIGGER IF EXISTS analytics_capture ON stock_receipts;
DROP TRIGGER IF EXISTS analytics_capture ON stock_receipt_lines;
DROP TRIGGER IF EXISTS analytics_capture ON stock_waste_events;
DROP TRIGGER IF EXISTS analytics_capture ON stock_waste_lines;
DROP TRIGGER IF EXISTS analytics_capture ON location_stock;
DROP TRIGGER IF EXISTS analytics_capture ON inventory_reorder_rules;
DROP TRIGGER IF EXISTS analytics_capture ON purchase_orders;
DROP TRIGGER IF EXISTS analytics_capture ON stock_transfer_requests;
DROP TRIGGER IF EXISTS analytics_capture ON stock_movements;
DROP FUNCTION IF EXISTS analytics_capture_change();
DROP TABLE IF EXISTS analytics_outbox;
